### ISSUE TITLE
Non effettua il controllo corretto per i CF delle onlus

### ISSUE THREAD

**Issue by filippomacchi** [lucavandro/CodiceFiscaleJS#11]
Ciao pensi sia possibile estendere il controllo anche alla verifica dei codici fiscali in uso per le onlus?

**Comment by lucavandro** [comment]
Ciao Filippo. Non saprei risponderti, in quanto sono venuto a conoscenza della questione solo leggendo dalla tua domanda.Ho provato a cercare online, ma non ho trovato documentazione a riguardo. Se possiedi qualche documento che spieghi come sia possibile effettuare tale calcolo, sentiti libero di condividerlo qui.

**Comment by filippomacchi** [comment]
Da quel che so i codici fiscali delle onlus sono numerici di 11 cifre e non vengono trattati come partite iva.
Sto cercando info anche io, appena trovo qualcosa di utile ti aggiorno.

**Comment by lucavandro** [comment]
Non avendo trovato documentazione a riguardo, ritengo che per il momento questa libreria posso essere utilizzata solo per le persone fisiche, dunque ritengo di poter chiudere questa issue.
