### ISSUE TITLE
Export changed from named to default in latest version

### ISSUE THREAD

**Issue by nerfologist** [lucavandro/CodiceFiscaleJS#14]
Hello,
in commit 50524230e9446742ed0dde8fe060ff0a29a819de (corresponding npm package version 2.1.0) the main export of this package has changed from named to default (https://github.com/lucavandro/CodiceFiscaleJS/commit/50524230e9446742ed0dde8fe060ff0a29a819de#diff-106dbfc8c2493a2f78072d7fc761456cL4).

It use to be
```
import { CodiceFiscale } from 'codice-fiscale-js';
```
Now it is
```
import CodiceFiscale from 'codice-fiscale-js'
```

I wanted to report this as it is an easy fix but also a non-backward-compatible change and should be a new major version according to best practices, anyway it should at least be mentioned in the documentation.

HTH

**Comment by lucavandro** [comment]
> Hello,
> in commit [5052423](https://github.com/lucavandro/CodiceFiscaleJS/commit/50524230e9446742ed0dde8fe060ff0a29a819de) (corresponding npm package version 2.1.0) the main export of this package has changed from named to default ([5052423#diff-106dbfc8c2493a2f78072d7fc761456cL4](https://github.com/lucavandro/CodiceFiscaleJS/commit/50524230e9446742ed0dde8fe060ff0a29a819de#diff-106dbfc8c2493a2f78072d7fc761456cL4)).
> 
> It use to be
> 
> ```
> import { CodiceFiscale } from 'codice-fiscale-js';
> ```
> Now it is
> 
> ```
> import CodiceFiscale from 'codice-fiscale-js'
> ```
> I wanted to report this as it is an easy fix but also a non-backward-compatible change and should be a new major version according to best practices, anyway it should at least be mentioned in the documentation.
> 
> HTH

Thank you. Docs have been fixed.
