### ISSUE TITLE
The CodicefiscaleJS is giving me 500 error

### ISSUE THREAD

**Issue by yesjosephraja** [lucavandro/CodiceFiscaleJS#19]
The CodicefiscaleJS is giving me 500 Internal Server Error.
When opening http://localhost/Luca/CodiceFiscaleJS-master/dist/codice.fiscale.var.js.

Please Help.

**Comment by lucavandro** [comment]
I guess it's something up with your local server not with the code in this repo.

**Comment by yesjosephraja** [comment]
Hi Luca,
Thanks for your reply. For some reason It was not working ( Giving 500 server error ) when I used the file "codice.fiscale.var.js" as it is. 
But it was working after changing the file name to "codicefiscalevar.js". Could be local server file name restriction or something.

Anyway Thanks for your effort to reply.

Best Regards
- Joseph Raja
