### ISSUE TITLE
comuni non aggiornati

### ISSUE THREAD

**Issue by ManuelSerra** [lucavandro/CodiceFiscaleJS#23]
Alcuni comuni risalenti al 2019 mancano (esempio: corigliano e rossano si sono fusi insieme cambiando codice, provincia di cosenza)

**Comment by lucavandro** [comment]
Salve, i dati fanno riferimento a quelli pubblicati su opendata nel 2016. Molti comuni sono stati fusi o hanno subito un cambio di provincia. L'idea è quella di inserire un meccanismo che, in base alla data di nascita inserita, riesca ad individuare il codice catastale giusto. Questo richiede di rivedere i dati di tutti i comuni per stabilirne la validità, ma al momento non ho modo di poterlo controllare personalmente e non sono riuscito a trovare un database che contenga questo tipo di informazioni. Sono graditi suggerimenti.

**Comment by lucavandro** [comment]
@andrpet @ManuelSerra ho appena aggiornato dagli ultimi dati ISTAT. Ho inserito anche uno script che consente di aggiornare automaticamente il progetto in caso variazioni future dei dati.
