### ISSUE TITLE
Fix labels in master/example/index.html

### ISSUE THREAD

**Issue by Mokei-it** [lucavandro/CodiceFiscaleJS#25]
First of all thank you for your great job!

**line 50:**
from:
&lt;label for="birthday"&gt;Gender&lt;/label&gt;
to:
&lt;label for="gender"&gt;Gender&lt;/label&gt;

**line 63:**
from:
&lt;label for="birthday"&gt;Birthplace province&lt;/label&gt;
to:
&lt;label for="birthplace_province"&gt;Birthplace province&lt;/label&gt;

**line 68:**
from:
&lt;label for="birthday"&gt;Birthplace&lt;/label&gt;
to:
&lt;label for="birthplace"&gt;Birthplace&lt;/label&gt;

**Comment by lucavandro** [comment]
Fixato. Grazie
