### ISSUE TITLE
Manca il codice della Jugoslavia (serbia-montenegro)

### ISSUE THREAD

**Issue by 9marta5** [lucavandro/CodiceFiscaleJS#29]
Manca il codice della Jugoslavia (serbia-montenegro) Z118.
Potete cortesemente inserirla? 

Grazie

**Comment by casagrandeg** [comment]
Ciao, il codice è presente in src ma non in lib. Credo basti ricompilare il progetto

**Comment by lucavandro** [comment]
L'errore è stato fixato dalla versione 2.2.5.
