### ISSUE TITLE
Codice fiscale per nati all'estero

### ISSUE THREAD

**Issue by simentesempre** [lucavandro/CodiceFiscaleJS#3]
Sarebbe ottimo se calcolasse anche i codici fiscali per i nati all'estero.
Per il calcolo serve solo il nome del paese, al posto del comune e della provincia.
La sigla geografica inizia con la Z e segue il codice del paese che ti metto in allegato per comodità se vuoi.
Grazie comunque ottimo lavoro.

[elencoStatiEsteriAttuali.zip](https://github.com/lucavandro/CodiceFiscaleJS/files/1276779/elencoStatiEsteriAttuali.zip)

**Comment by simentesempre** [comment]
Per comodità li ho anche già formattati se vi servono

EE:[["ALBANIA","Z100"],
["ANDORRA","Z101"],
["AUSTRIA","Z102"],
["BELGIO","Z103"],
["BULGARIA","Z104"],
["CITTA' DEL VATICANO","Z106"],
["DANIMARCA","Z107"],
["FAER OER (ISOLE)","Z108"],
["FINLANDIA","Z109"],
["FRANCIA","Z110"],
["GERMANIA","Z112"],
["GIBILTERRA","Z113"],
["REGNO UNITO","Z114"],
["GRECIA","Z115"],
["IRLANDA","Z116"],
["ISLANDA","Z117"],
["LIECHTENSTEIN","Z119"],
["LUSSEMBURGO","Z120"],
["MALTA","Z121"],
["MAN (ISOLA)","Z122"],
["MONACO","Z123"],
["ISOLE DEL CANALE","Z124"],
["NORVEGIA","Z125"],
["PAESI BASSI","Z126"],
["POLONIA","Z127"],
["PORTOGALLO","Z128"],
["ROMANIA","Z129"],
["SAN MARINO","Z130"],
["SPAGNA","Z131"],
["SVEZIA","Z132"],
["SVIZZERA","Z133"],
["UNGHERIA","Z134"],
["UCRAINA","Z138"],
["BIELORUSSIA","Z139"],
["MOLDAVIA","Z140"],
["ESTONIA","Z144"],
["LETTONIA","Z145"],
["LITUANIA","Z146"],
["MACEDONIA","Z148"],
["CROAZIA","Z149"],
["SLOVENIA","Z150"],
["BOSNIA ED ERZEGOVINA","Z153"],
["FEDERAZIONE RUSSA","Z154"],
["SLOVACCHIA","Z155"],
["REPUBBLICA CECA","Z156"],
["KOSOVO","Z160"],
["TERRITORI PALESTINESI","Z161"],
["AFGHANISTAN","Z200"],
["ARABIA SAUDITA","Z203"],
["BAHREIN","Z204"],
["BHUTAN","Z205"],
["MYANMAR","Z206"],
["BRUNEI","Z207"],
["CAMBOGIA","Z208"],
["SRI LANKA","Z209"],
["CINA REPUBBLICA POPOLARE","Z210"],
["CIPRO","Z211"],
["COCOS (ISOLE)","Z212"],
["REPUBBLICA DI COREA","Z213"],
["COREA DEL NORD","Z214"],
["EMIRATI ARABI UNITI","Z215"],
["FILIPPINE","Z216"],
["TAIWAN","Z217"],
["GAZA (TERRITORIO DI)","Z218"],
["GIAPPONE","Z219"],
["GIORDANIA","Z220"],
["INDIA","Z222"],
["INDONESIA","Z223"],
["IRAN","Z224"],
["IRAQ","Z225"],
["ISRAELE","Z226"],
["KUWAIT","Z227"],
["LAOS","Z228"],
["LIBANO","Z229"],
["MACAO","Z231"],
["MALDIVE","Z232"],
["MONGOLIA","Z233"],
["NEPAL","Z234"],
["OMAN","Z235"],
["PAKISTAN","Z236"],
["QATAR","Z237"],
["SIRIA","Z240"],
["THAILANDIA","Z241"],
["TURCHIA","Z243"],
["YEMEN","Z246"],
["MALAYSIA","Z247"],
["SINGAPORE","Z248"],
["BANGLADESH","Z249"],
["VIETNAM","Z251"],
["ARMENIA","Z252"],
["AZERBAIGIAN","Z253"],
["GEORGIA","Z254"],
["KAZAKHSTAN","Z255"],
["KIRGHIZISTAN","Z256"],
["TAGIKISTAN","Z257"],
["TURKMENISTAN","Z258"],
["UZBEKISTAN","Z259"],
["NAMIBIA","Z300"],
["ALGERIA","Z301"],
["ANGOLA","Z302"],
["BURUNDI","Z305"],
["CAMERUN","Z306"],
["CAPO VERDE","Z307"],
["CENTRAFRICANA REPUBBLICA","Z308"],
["CIAD","Z309"],
["COMORE","Z310"],
["CONGO REPUBBLICA POPOLARE","Z311"],
["CONGO REPUBBLICA DEMOCRATICA","Z312"],
["COSTA D'AVORIO","Z313"],
["BENIN","Z314"],
["ETIOPIA","Z315"],
["GABON","Z316"],
["GAMBIA","Z317"],
["GHANA","Z318"],
["GUINEA","Z319"],
["GUINEA BISSAU","Z320"],
["GUINEA EQUATORIALE","Z321"],
["KENYA","Z322"],
["LA REUNION (ISOLA)","Z324"],
["LIBERIA","Z325"],
["LIBIA","Z326"],
["MADAGASCAR","Z327"],
["MALAWI","Z328"],
["MALI","Z329"],
["MAROCCO","Z330"],
["MAURITANIA","Z331"],
["MAURIZIO","Z332"],
["MOZAMBICO","Z333"],
["NIGER","Z334"],
["NIGERIA","Z335"],
["EGITTO","Z336"],
["ZIMBABWE","Z337"],
["RUANDA","Z338"],
["SANT'ELENA (ISOLA)","Z340"],
["SAO TOME' E PRINCIPE","Z341"],
["SEICELLE","Z342"],
["SENEGAL","Z343"],
["SIERRA LEONE","Z344"],
["SOMALIA","Z345"],
["SUDAFRICANA REPUBBLICA","Z347"],
["SUDAN","Z348"],
["SWAZILAND","Z349"],
["TOGO","Z351"],
["TUNISIA","Z352"],
["UGANDA","Z353"],
["BURKINA FASO","Z354"],
["ZAMBIA","Z355"],
["TANZANIA","Z357"],
["BOTSWANA","Z358"],
["LESOTHO","Z359"],
["MAYOTTE (ISOLA)","Z360"],
["GIBUTI","Z361"],
["ERITREA","Z368"],
["BERMUDA (ISOLE)","Z400"],
["CANADA","Z401"],
["GROENLANDIA","Z402"],
["SAINT PIERRE ET MIQUELON (ISOLE)","Z403"],
["STATI UNITI D'AMERICA","Z404"],
["ANTILLE OLANDESI","Z501"],
["BAHAMAS","Z502"],
["COSTA RICA","Z503"],
["CUBA","Z504"],
["REPUBBLICA DOMINICANA","Z505"],
["EL SALVADOR","Z506"],
["GIAMAICA","Z507"],
["GUADALUPA","Z508"],
["GUATEMALA","Z509"],
["HAITI","Z510"],
["HONDURAS","Z511"],
["BELIZE","Z512"],
["MARTINICA","Z513"],
["MESSICO","Z514"],
["NICARAGUA","Z515"],
["PANAMA","Z516"],
["PANAMA ZONA DEL CANALE","Z517"],
["PUERTO RICO","Z518"],
["TURKS E CAICOS (ISOLE)","Z519"],
["VERGINI AMERICANE (ISOLE)","Z520"],
["BARBADOS","Z522"],
["GRENADA","Z524"],
["VERGINI BRITANNICHE (ISOLE)","Z525"],
["DOMINICA","Z526"],
["SAINT LUCIA","Z527"],
["SAINT VINCENT E GRENADINE","Z528"],
["ANGUILLA (ISOLA)","Z529"],
["CAYMAN (ISOLE)","Z530"],
["MONTSERRAT","Z531"],
["ANTIGUA E BARBUDA","Z532"],
["SAINT KITTS E NEVIS","Z533"],
["ARGENTINA","Z600"],
["BOLIVIA","Z601"],
["BRASILE","Z602"],
["CILE","Z603"],
["COLOMBIA","Z604"],
["ECUADOR","Z605"],
["GUYANA","Z606"],
["GUIANA FRANCESE","Z607"],
["SURINAME","Z608"],
["FALKLAND (ISOLE)","Z609"],
["PARAGUAY","Z610"],
["PERU'","Z611"],
["TRINIDAD E TOBAGO","Z612"],
["URUGUAY","Z613"],
["VENEZUELA","Z614"],
["AUSTRALIA","Z700"],
["CHRISTMAS (ISOLA)","Z702"],
["COOK (ISOLE)","Z703"],
["VITI","Z704"],
["GUAM (ISOLA)","Z706"],
["IRIAN OCCIDENTALE","Z707"],
["MACQUARIE (ISOLE)","Z708"],
["MARIANNE (ISOLE)","Z710"],
["MARSHALL","Z711"],
["MIDWAY (ISOLE)","Z712"],
["NAURU","Z713"],
["SAVAGE (ISOLE)","Z714"],
["NORFOLK (ISOLE E ISOLE DEL MAR DEI CORALLI)","Z715"],
["NUOVA CALEDONIA (ISOLE E DIPENDENZE)","Z716"],
["NUOVA ZELANDA","Z719"],
["ISOLE CILENE (PASQUA E SALA Y GOMEZ)","Z721"],
["PITCAIRN (E DIPENDENZE)","Z722"],
["POLINESIA FRANCESE (ISOLE)","Z723"],
["SALOMONE","Z724"],
["SAMOA AMERICANE (ISOLE)","Z725"],
["SAMOA","Z726"],
["ISOLE DELL'UNIONE","Z727"],
["TONGA","Z728"],
["WALLIS E FUTUNA (ISOLE)","Z729"],
["PAPUA NUOVA GUINEA","Z730"],
["KIRIBATI","Z731"],
["TUVALU","Z732"],
["VANUATU","Z733"],
["PALAU","Z734"],
["MICRONESIA STATI FEDERATI","Z735"],
["DIPENDENZE CANADESI","Z800"],
["DIPENDENZE NORVEGESI ARTICHE","Z801"],
["DIPENDENZE RUSSE","Z802"],
["DIPENDENZE AUSTRALIANE","Z900"],
["DIPENDENZE BRITANNICHE","Z901"],
["DIPENDENZE FRANCESI","Z902"],
["DIPENDENZE NEOZELANDESI","Z903"],
["DIPENDENZE NORVEGESI ANTARTICHE","Z904"],
["DIPENDENZE STATUNITENSI","Z905"],
["DIPENDENZE SUDAFRICANE","Z906"],
["SUD SUDAN","Z907"]]

**Comment by lucavandro** [comment]
@simentesempre grazie dell'ottimo suggerimento. Provvedo quanto prima ad integrare la tua richiesta.

**Comment by lucavandro** [comment]
@simentesempre ho aggiunto il supporto per i nati all'estero
