### ISSUE TITLE
Manca il Codice Catastale del comune di Contarina

### ISSUE THREAD

**Issue by DavideBonfanti** [lucavandro/CodiceFiscaleJS#34]
Il codice **C967** manca perché il comune di **Contarina** è stato fuso nel 1995, ma per i nati prima di quella data sarebbe un codice valido
https://www.ilcodicefiscale.it/codici-catastali-comunali.php?comune=CONTARINA

**Comment by lucavandro** [comment]
Aggiunto dalla versione 2.2.5
