### ISSUE TITLE
Error omocodie with foreign fiscal code 

### ISSUE THREAD

**Issue by gianlucavillani** [lucavandro/CodiceFiscaleJS#35]
Cannot reverse omocodian fiscal code for non-italian person. If I try to reverse the fiscal code returned from the method "omocodie()" for non-italin person it doesn't work. Tried for Russian citizen.

**Comment by lucavandro** [comment]
Made some tests: it's seems working. Would you be so kind and provide further details? Feel free to get in touch via email lucavandro@gmail.com

**Comment by gianlucavillani** [comment]
Ho fatto altri testi e ora funziona anche a me. Il problema era dovuto al fatto che npm installava la versione 2.2.4 e non la 2.2.5 molto probabilmente. Ieri comunque neanche sulla tua pagina web il reverse di un omocodie straniero funzionava. Oggi sembra che tutto funziona

**Comment by lucavandro** [comment]
OK. Allora possiamo considerare la questione conclusa.
