### ISSUE TITLE
Codifica e Decodifica non simmetriche

### ISSUE THREAD

**Issue by DavideBonfanti** [lucavandro/CodiceFiscaleJS#37]
La codifica e successiva decodifica degli stessi dati non generano stringhe comparabili sul codice catastale se il comune è in uno specifico insieme, ad es.
```
Mario
Rossi
Male
25/12/1980
Piacenza
Calendasco
```
genera il codice **RSSMRA80T25B404V** che viene però decodificato con

```
MRA
RSS
M
1980-12-25
TN
CALDONAZZO
```
dato che il codice catastale corretto di Calendasco sarebbe **B405**

ho provato anche nella [pagina di test](https://lucavandro.github.io/CodiceFiscaleJS/).

**Comment by lucavandro** [comment]
Ciao grazie per la tua segnalazione. Il bug è stato risolto nell'ultima versione. Se questa libreria ti è stata utile, ti prego di lasciare una stellina.
