### ISSUE TITLE
La lista dei comuni della provincia di Olbia-Tempio è vuota

### ISSUE THREAD

**Issue by Fragger5000** [lucavandro/CodiceFiscaleJS#38]
Innanzitutto complimenti per il tuo lavoro, volevo segnalarti che la lista dei comuni della provincia di Olbia-Tempio è vuota, questo si verifica anche nella pagina di esempio

![lT69Nl8olv](https://user-images.githubusercontent.com/22413422/87294996-d7d7b300-c504-11ea-96c8-6c795cca16e0.png)

**Comment by Fragger5000** [comment]
Vedo che è stata abolita nel 2016 :-) https://it.wikipedia.org/wiki/Provincia_di_Olbia-Tempio, magari andrà tolta da lista-province.js

**Comment by lucavandro** [comment]
Ciao. Come correttamente rilevata la privincia è stata abolita, verrà quindi rimossa dall'elenco
