### ISSUE TITLE
Reverse del Codice Fiscale

### ISSUE THREAD

**Issue by marcore86** [lucavandro/CodiceFiscaleJS#42]
il calcolo del reverse del codice fiscale risulta essere errato nel caso in cui una persona abbia almeno 100 anni.
Di seguito un esempio: 

<img width="1197" alt="Schermata 2020-08-09 alle 1 16 17 PM" src="https://user-images.githubusercontent.com/10436263/89730855-d4bbde00-da42-11ea-8547-91e334b3855e.png">

**Comment by lucavandro** [comment]
L'algoritmo del calcolo del codice fiscale, per come è stato concepito, considera solo le ultime due cifre dell'anno di nascita, quindi nel reverse non c'è modo di discriminare tra chi è nato nel XX o nel XXI secolo. Come scelta implementativa nel metodo "reverse" si è scelto di considerare solo le persone con meno di 100 anni. 

[qui trovi maggiori info sul funzionamento dell'algoritmo](https://immoplus.it/codice-fiscale/)
