### ISSUE TITLE
Ordine alfabetico delle voci di menu

### ISSUE THREAD

**Issue by Fragger5000** [lucavandro/CodiceFiscaleJS#45]
Scorrendo le voci di menu delle procvince sembra che la provincia di Crotone non ci sia

![image_2020_09_17T08_33_55_697Z](https://user-images.githubusercontent.com/22413422/93449698-579f4680-f8d5-11ea-8529-0af155a53a24.png)

in realtà la provincia di Crotone ha come sigla KR e, giustamente, si trova sotto Isernia. Dato che però alcuni utenti, non colgono questa sottigliezza io risolverei con l'autocomplete di jquery ui 

https://jqueryui.com/autocomplete/#combobox

filtrando sul valore e non sulla chiave
https://github.com/lucavandro/CodiceFiscaleJS/blob/master/src/lista-province.js

ci sono eventuali controindicazioni?

**Comment by lucavandro** [comment]
Salve Francesco, grazie della segnalazione. Trova la correzione nella versione v2.3.3 (attuale master) e disponibile anche su npm.
Per il momento non prevedo l'utilizzo di jQuery UI, al fine di mantenere il progetto indipendente da altre librerie, però non ci sono controindicazioni se tu volessi farne uso. 
Se lo ritieni opportuno, lasceresti una stellina ⭐ al progetto ?

**Comment by Fragger5000** [comment]
già messa :-)
