### ISSUE TITLE
Errore nella creazione codice fiscale da codice catastale

### ISSUE THREAD

**Issue by nightwolfy** [lucavandro/CodiceFiscaleJS#46]
Ciao, intanto complimenti per la libreria, la trovo veramente utilissima.
Arrivo dalla versione 2.2.4 ed aggiornato all'ultima versione ho notato che in quest'ultima se provo a creare un codice fiscale dai dati come nell'esempio qui sotto

` 
const cf = CodiceFiscale.compute({
      name: "mario",
      surname: "rossi",
      gender: "M",
      birthday: "2000-01-01",
      birthplace: "H501"
    });
`

produce il seguente errore: 

`Comune with name of H501 is found in more than one province. Please specify the province code`

Guardando il codice sembra che nel costruttore della classe Comune non trovando un comune col nome H501 non proceda al metodo che ricerca il comune per CC. A me torna molto più utile la ricerca per codice catastale per quello procedo con quella nella creazione. 
Se posso suggerire una possibile soluzione si potrebbe mettere nel constructor il metodo searchByNameAndProvince sotto try catch ed inizializzare la variabile comune ad undefined in caso di errore. Cosi dovrebbe procedere alla ricerca per CC col metodo searchByCC.

**Comment by lucavandro** [comment]
Ciao,

l'argomento birthplace non è pensato per contenere il codice catastale, ma il nome del comune di nascita. Comunque, ho introdotto il fallback da te consigliato (penso che non faccia del male a nessuno 🙏).  
Trovi tutto nella versione 2.3.5 
Se questo progetto ti è stato utile, potresti lasciare una ⭐per mostrarci il tuo sostegno? Grazie!

**Comment by nightwolfy** [comment]
Stella già lasciata, grazie per il fix lampo!
