### ISSUE TITLE
Import della libreria con require non funzionante

### ISSUE THREAD

**Issue by simoneBrancati** [lucavandro/CodiceFiscaleJS#47]
Premettendo che utilizzo la libreria con NodeJS, la versione 2.3.5 ha introdotto il seguente bug:

`Uncaught TypeError: CodiceFiscale.check is not a function`

Per riprodurlo:

```js
const CodiceFiscale = require('codice-fiscale-js');
CodiceFiscale.check('MRNLCU00A01H501');
```

Presumo che il problema sia stato introdotto dal commit 38d4d54f9392cc026edac6fda81c9703bcbcf716 .

**Comment by lucavandro** [comment]
Ciao. Ti ringrazio della segnalazione. Con la versione 2.3.6 il problema è stato rimosso. Per node.js, ti consiglio di dare uno sguardo [alla versione di questa libreria specifica per node]( https://github.com/lucavandro/CodiceFiscaleJS-node), che rispetto a questa, è molto più performante.

P.S. Se questa libreria ti è stata utile, considera di supportarla lasciando una ⭐ alla repo. Grazie
