### ISSUE TITLE
Uncaught Error: Comune with name of CHIARAVALLE and prov AN doesn't exists

### ISSUE THREAD

**Issue by xabaras** [lucavandro/CodiceFiscaleJS#48]
Non riesco a calcolare il codice fiscale per una paersona nata a Chiaravalle in provincia di Ancona.
Ottengo sempre questo errore:

Uncaught Error: Comune with name of CHIARAVALLE and prov AN doesn't exists. Left:3403 Right:3403 

codice.fiscale.var.js:1:923681

**Comment by lucavandro** [comment]
Ciao. Questo errore viene generato da una vecchia versione della libreria. Prova ad utilizzare l'ultima versione (2.3.6).

P.S. Se questa libreria ti è stata utile, considera di supportarla lasciando una ⭐ alla repo. Grazie

**Comment by xabaras** [comment]
Grazie. con la nuova versione funziona.

Già lasciato la ⭐

;-)
