### ISSUE TITLE
Il sito di esempio non funziona

### ISSUE THREAD

**Issue by lulibo** [lucavandro/CodiceFiscaleJS#49]
Ciao,
volevo segnalare che il sito di esempio (https://lucavandro.github.io/CodiceFiscaleJS/) non funziona né su chrome né su safari. Premo su submit e non accade nulla.

**Comment by lucavandro** [comment]
Ciao @lulibo . Grazie per la tua segnalazione! Il sito d'esempio ora è funzionante. Ti chiedo scusa per il disagio.
