### ISSUE TITLE
Nome del file per inclusione in browser

### ISSUE THREAD

**Issue by devsware** [lucavandro/CodiceFiscaleJS#50]
Salve, volevo segnalare un potenziale problema con il nome del file per l'inclusione diretta dello script nel browser(`codice.fiscale.var.js`).

In Apache, se è attivo il modulo `mod_negotiation`, i file il cui nome contiene `.var` (è sufficiente che sia presente dentro il nome del file, non è necessariamente l'estensione finale) vengono interpretati come type-maps e quando Apache trova  al suo interno del codice JavaScript invece delle direttive per le type-maps viene generato un errore 500 invece di servire il file.

Lato server, in questo caso dovrebbe essere disabilitato il modulo oppure aggiunta una direttiva all'interno della configurazione del Virtual Host per rimuovere il controllo sui file `.var`, ma queste operazioni potrebbero non essere possibili su hosting di terze parti con il `mod_negotiation` attivo, ed in questo caso la libreria non potrebbe essere utilizzata se non cambiando a mano il nome del file; in questo modo però si "sporcherebbe" la directory qualora sia stata aggiunta con npm o yarn, con il rischio che la modifica venga comunque rimossa ad un successivo update.

Lo stesso file che fa generare l'errore 500, semplicemente variato usando un nome che non contiene il `.var` al suo interno (ad esempio `codice.fiscale.js` oppure `codice-fiscale-var.js`) viene invece correttamente servito da Apache senza alcun errore.

**Comment by lucavandro** [comment]
Ciao. Ho inserito una seconda versione del file con il nome "codice-fiscale-var.js" che sarà ovviamente presente in tutte le versioni successive
