### ISSUE TITLE
 birthplace name or code

### ISSUE THREAD

**Issue by laerte8** [lucavandro/CodiceFiscaleJS#52]
hello,
I have a question about the birthplace.
in page the option elements are like this:
<option value="A010">Abbiategrasso</option>
I used CodiceFiscale.utils.birthplaceFields("#birthplace_province", "#birthplace"); to build the select
the value is A010, so, if I use e.target.value it returns A010.

but if i create a new CodiceFiscaleJS({...data,birthdate:A010}) it returns an error because it expects Abbiategrasso as value.

how can I get the birthplace name and not the code?
thanks

**Comment by lucavandro** [comment]
Hi!
The problem is this
new CodiceFiscaleJS({...data,**birthdate**:A010}`
you should use **birthplace** in that place. 
`new CodiceFiscaleJS({...data,**birthplace**:A010})`

I hope this could help
