### ISSUE TITLE
Anno da desktop 6 cifre

### ISSUE THREAD

**Issue by metiusat** [lucavandro/CodiceFiscaleJS#57]
Ciao Luca,

da desktop si riuscirebbe a limitare l'anno a 4 cifre? e nel caso il top sarebbe con controllo sulle prime due cifre dell'anno 19 o 20 

![image](https://user-images.githubusercontent.com/6828521/106173740-8fc46900-6194-11eb-8efb-4472aceccf98.png)

**Comment by lucavandro** [comment]
Ciao. In realtà quello che cerchi di ottenere non dipende dalla libreria, ma è un'impostazione del tag html <input type="date"> utilizzando gli attributi min e max.
Per farla breve per ottenere quello che cerchi potresti fare così
```html
<input type="date" id="birthday" name="birthday" min="1900-01-01" max="2099-01-01" required>
```

se vuoi rendere dinamica la data "massima", per impostarla ad esempio pari alla data odierna, puoi usare una semplice riga di JS

```js
document.getElementById("birthday").max = new Date().toISOString().slice(0,10)
```
