### ISSUE TITLE
Bug omocodie e toString()

### ISSUE THREAD

**Issue by andryc99** [lucavandro/CodiceFiscaleJS#58]
Se viene chiamato il metodo `toString()` dopo aver chiamato il metodo `omocodie()` sullo stesso oggetto `CodiceFiscale`, manca il `checkCode`.
Ad esempio l'output di questo codice
```javascript
let cf = new CodiceFiscale({
            name: "Mario",
            surname: "Rossi",
            gender: "M",
            birthday: "1987-02-01",
            birthplace: "H501"
        });

console.log(cf.toString());
cf.omocodie();
console.log(cf.toString());
```
è
```
RSSMRA87B01H501A
RSSMRA87B01H501
```
Come si può vedere, nel secondo output manca il `checkCode`.

**Comment by lucavandro** [comment]
Ciao. Grazie della segnalazione. Il bug è stato risolto con la versione 2.3.8
