### ISSUE TITLE
Elenco province non aggiornato

### ISSUE THREAD

**Issue by simentesempre** [lucavandro/CodiceFiscaleJS#6]
Ciao, sto utilizzando il vostro script, funziona benissimo. Purtroppo un cliente mi ha fatto notare una possibile lacuna (che ho effettivamente verificato e riscontrato) nell'elenco province e comuni: ossia che è probabile che non siano aggiornati.
Ad esempio noto la mancanza della provincia "Monza e Brianza", con sigla "MB", istituita nel 2004.
Credo si renda necessario uno check delle province inserite nel json e anche nel js minificato.
Buon lavoro

**Comment by simentesempre** [comment]
Ho analizzato il json e identificato le province mancanti.

BT Barletta Andria Trani
CI Carbonia Iglesias
FM Fermo
MB Monza Brianza
VS Medio Campidano
OG Ogliastra
OT Olbia Tempio

Creo dei JSON da condividervi

**Comment by simentesempre** [comment]
[bt.txt](https://github.com/lucavandro/CodiceFiscaleJS/files/1378795/bt.txt)
[ci.txt](https://github.com/lucavandro/CodiceFiscaleJS/files/1378796/ci.txt)
[fm.txt](https://github.com/lucavandro/CodiceFiscaleJS/files/1378797/fm.txt)
[vs.txt](https://github.com/lucavandro/CodiceFiscaleJS/files/1378798/vs.txt)
[mb.txt](https://github.com/lucavandro/CodiceFiscaleJS/files/1378799/mb.txt)
[og.txt](https://github.com/lucavandro/CodiceFiscaleJS/files/1378800/og.txt)
[ot.txt](https://github.com/lucavandro/CodiceFiscaleJS/files/1378801/ot.txt)

**Comment by simentesempre** [comment]
Naturalmente i comuni che si raggruppano in queste nuove sette province andrebbero rimossi dalle province in cui si trovavano prima, ma capisco che sia un lavoro lungo, e anche se non viene fatto ho già verificato che non crea problemi, rimangono silenti e innocui nelle vecchie province.
Buon lavoro

**Comment by lucavandro** [comment]
Ciao ho integrato le province mancanti, tranne quelle sarde che sono state abolite nel 2016.
