### ISSUE TITLE
Check Fiscal Code

### ISSUE THREAD

**Issue by adilorenzodema** [lucavandro/CodiceFiscaleJS#71]
Hi!
How I can verify, in typescript, if a fiscal code is valid or invalid?
Hi try with 'try catch', do you known a better method?

`try {
        cf = new CodiceFiscale(control.value);
        return true;
      } catch (error) {
        return  false
      }
`

**Comment by lucavandro** [comment]
Hi! 
`CodiceFiscale.check(control.value)`
this will return a boolean
