### ISSUE TITLE
Runtime error with TypeScript

### ISSUE THREAD

**Issue by DenisFrezzato** [lucavandro/CodiceFiscaleJS#72]
After updating to `2.3.10`, I got this error: `TypeError: 'codice_fiscale_js_1.default is not a constructor'`

To reproduce: [playground](https://codesandbox.io/s/frosty-knuth-de4t4?file=/src/index.ts)

`2.3.9` was fine.

**Comment by ste7en** [comment]
I experienced the same problem. Had to downgrade to `2.3.9`

**Comment by Maverick283** [comment]
Can confirm, same issue here.

**Comment by lucavandro** [comment]
Fixed in v2.3.13. Please upgrade
