### ISSUE TITLE
Dati comuni

### ISSUE THREAD

**Issue by dotPIX** [lucavandro/CodiceFiscaleJS#75]
Ciao @lucavandro, ti ringrazio per la tua preziosa utility.
Pochi giorni fa mi è capitato di fare testing su una lista di codici fiscali, tra cui questo: RSSMRA90P50Z258M (ho cambiato nome e cognome). Facendo un controllo appare come corretto ma nel caso voglia creare il codice fiscale inserendo i dati singolarmente (reverse) mi da errore "Comune with name of TURKMENISTAN and prov EE doesn't exists".
Andando a guardare la lista comuni mi sono accorto che utilizzi degli oggetti col valore del comune, codice provincia, nome comune ed un ulteriore campo binario. Per il TURKMENISTAN ci sono due oggetti con codice provincia diverso ma lo stesso codice binario (zero).
Analizzando il codice ho capito che questo campo binario lo usi per decidere quale comune prendere come default. Però in questo caso, essendo entrambi zero, non mi ritorna nulla e va in errore.
Per esempio anche il comune TRANI ha due oggetti ma uno di questi ha il campo binario a 1.
Quel valore andrebbe corretto o mi sfugge qualcosa?
Ti ringrazio.

**Comment by dotPIX** [comment]
grazie per la celerità ;)

**Comment by lucavandro** [comment]
Se lo riteni oppurtuno, mi farebbe piacere se lasciassi una stellina alla repo. Grazie
