### ISSUE TITLE
Gestione storico province

### ISSUE THREAD

**Issue by pigreco33** [lucavandro/CodiceFiscaleJS#78]
Salve, utilizzando la libreria mi sono accorto che non viene gestito lo storico dei codici Belfiore (codici comuni).
Il codice fiscale di una persona fisica viene creato a partire dalla "fotografia geopolitica" alla data di nascita del soggetto, come da specifiche dell'Agenzia delle Entrate.
Questo fa sì che debba essere necessario validare il codice fiscale calcolando il codice comune così com'era alla data di nascita.

A titolo di esempio, il comune di Biella è in provincia di Biella solo dal 1992, prima era in provincia di Vercelli e prima ancora di Novara.
La libreria non riesce a validare un codice fiscale di una persona nata a Biella prima del 1992 perché considera come unica provincia associata a quel comune la provincia di Biella (BI).

A disposizione per chiarimenti ed aiuto nell'implementazione e/o recupero delle informazioni.

Grazie

**Comment by lucavandro** [comment]
Ciao @pigreco33 . Si, la libreria non gestisce lo storico dei codici, per due motivi:

1. Non abbiamo a disposizione una fonte che attesti e riporti in maniera affidabile questo storico
2. Anche avendo a disposizione i dati al punto uno, inglobarli all'interno della libreria comporterebbe un aumento delle dimensioni della stessa e che al momento sono già a limite.
