### ISSUE TITLE
Wrong date of birth

### ISSUE THREAD

**Issue by pchlsn90** [lucavandro/CodiceFiscaleJS#84]
Hi,
I found an issue, if you put the timezone of the pc on a timezone in next day (i.e. from Italy you put Fiji) you'll receive a wrong date of birth.

example:
CF: ******73H67D08**
birthDay: 26/06/1973 (the correct date is 27/06/1973)

the current hour in italy at the time oh the screenshot is 09/06/2022 09:40

<img width="367" alt="image" src="https://user-images.githubusercontent.com/85675767/172792787-8c435c7a-e2ed-43f4-988e-da5a0fe1c9c2.png">

**Comment by pchlsn90** [comment]
I analized the 'reverse' function, a possible solution is to transform
this line:
this.birthday = new Date(Date.UTC(year, month, day, 0, 0, 0, 0))
in:
this.birthday = new Date(year, month, day, 0, 0, 0, 0)

**Comment by pchlsn90** [comment]
I also found this solution on stack owerflow:
https://stackoverflow.com/a/16048201

**Comment by lucavandro** [comment]
Thank you for your report. This issue will be fixed starting from v.2.3.19
