### ISSUE TITLE
Riga duplicata in lista-comuni.js comune CONTARINA(RO)

### ISSUE THREAD

**Issue by maxpoto** [lucavandro/CodiceFiscaleJS#97]
Sarebbe possibile eliminare la riga ?
https://github.com/lucavandro/CodiceFiscaleJS/blob/b5217b7fa596238e03ff1e07edec0eeacd0fe3a4/src/lista-comuni.js#L3856

è una duplicazione errata per il comune di Contarina che non è nella provincia di TV.

Grazie

**Comment by lucavandro** [comment]
Si, hai ragione. Provvedo
