### ISSUE TITLE
Problema omocodia. Data errata.

### ISSUE THREAD

**Issue by simsar78** [lucavandro/CodiceFiscaleJS#98]
Ciao,
con un codice fiscale inerente un omocodia mi ritorna una data diversa rispetto a quella reale e quindi il check non va a buon fine.

Come posso risolvere tale problematica ?

Grazie e buone cose.
Simone

**Comment by Lucabenj** [comment]
> Ciao, con un codice fiscale inerente un omocodia mi ritorna una data diversa rispetto a quella reale e quindi il check non va a buon fine.

Idem

**Comment by EliaMinozzi** [comment]
Ciao @simsar78 questo progetto è ormai abbandonato, ti conviene correggerlo da codice lato tuo. 
Io per esempio uso la libreria su un form in cui l'utente deve inserire il codice fiscale e tutti i dati ad esse inerenti, e per verificare la correttezza della data di nascita vedo se quanto esce dalla libreria (ovvero dal metodo CodiceFiscale.computeInverse(fiscalCode_value) ha l'anno uguale alla data di nascita inserita oppure se l'anno che ti da come output CodiceFiscale.computeInverse meno 100 è uguale all'anno della data di nascita inserita.

**Comment by lucavandro** [comment]
@EliaMinozzi il progetto non è abbandonato, ma come tutti i progetti opensource, lo seguo quando e se ho tempo e voglia. 
Le issue come quelle di @simsar78 sono molto vaghe: senza il codice fiscale che genera il problema è impossibile individuarne la causa. Se non lo si può postare qui, basta inviarmelo in privato via mail.
Se ci sono delle fix che si ritengono utili, anzichè fare delle fork o modificare il codice "lato tuo" si possono inviare delle pull request. 
Non lo dico con saccenza o superbia, ma è l'unico modo per far andare avanti i progetti open-souerce.

**Comment by EliaMinozzi** [comment]
Ciao @lucavandro si, scusami ho confuso questo repo con un altro repo che guardo spesso in cui lo sviluppatore ha dichiarato di aver abbandonato il progetto. Penso che l'issue presentato sia relativo a codici fiscali di persone nate più di 100 anni fa. A me è capitato questo caso oggi:
Mario Rossi
Nato a Milano (MI) il 01/01/2019, potenzialmente ha un codice fiscale molto simile a quello di Mario Rossi nato a Milano(MI) il 01/01/1919, questo perché l'indicazione dell'anno di nascita all'interno del codice fiscale è relativo solo alle ultime due cifre e quindi non c'èun indicazione del secolo. Per cui se si inserisce il codice fiscale nella funzione CodiceFiscale.computeInverse viene restituito come anno di nascita sempre il 2019. Per gestire questi casi penso che bisognerebbe proprio cambiare la struttura dell'oggetto che ritorna computeInverse e far tornare un array di anni e/o di date di nascita invece di un singolo valore.
Ci tengo ancora a scusarmi per il mio malinteso e ci tengo a precisare che quello proposto è solo un workaround, nei prossimi giorni infatti se dovessi aver tempo mi piacerebbe collaborare con una pull request.
